---
# Reference:
# https://help.github.com/en/github/building-a-strong-community/\
#   configuring-issue-templates-for-your-repository
blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Contributing Policy
    url: https://github.com/pheus/netbox-aci-plugin/blob/main/CONTRIBUTING.md
    about: >
      Please read through our contributing policy before opening an issue or
      pull request.
  - name: â“ Discussion
    url: https://github.com/pheus/netbox-aci-plugin/discussions
    about: >
      If you're just looking for help, try starting a discussion instead.
...
